# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d444f9b21e432133bb3383518ec65438622f8a1156292f59f70d978f3621948e211902739c31554a7fd849547637c79fa6ba3b0f3225e82052380c172320bea

test:
  secret_key_base: 005184721da60e4ba466d6af1c2e7869a8056f8ed5cb6fa37b52e6fe05413b420580e971fb504169bcfdcfd2d471d8d3aaba73aa580a4b7989edb9698877e132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
